// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/factory/protos/packet.proto

package factory

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketType int32

const (
	PacketType_PACKET_TYPE_UNSPECIFIED PacketType = 0
	PacketType_PACKET_TYPE_REQUEST     PacketType = 1
	PacketType_PACKET_TYPE_RESPONSE    PacketType = 2
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "PACKET_TYPE_UNSPECIFIED",
		1: "PACKET_TYPE_REQUEST",
		2: "PACKET_TYPE_RESPONSE",
	}
	PacketType_value = map[string]int32{
		"PACKET_TYPE_UNSPECIFIED": 0,
		"PACKET_TYPE_REQUEST":     1,
		"PACKET_TYPE_RESPONSE":    2,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_factory_protos_packet_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_core_factory_protos_packet_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_core_factory_protos_packet_proto_rawDescGZIP(), []int{0}
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          PacketType             `protobuf:"varint,2,opt,name=type,proto3,enum=factory.PacketType" json:"type,omitempty"`
	TargetIoType  string                 `protobuf:"bytes,3,opt,name=target_io_type,json=targetIoType,proto3" json:"target_io_type,omitempty"`
	Context       *Context               `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         *Error                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_core_factory_protos_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_core_factory_protos_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_core_factory_protos_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Packet) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_PACKET_TYPE_UNSPECIFIED
}

func (x *Packet) GetTargetIoType() string {
	if x != nil {
		return x.TargetIoType
	}
	return ""
}

func (x *Packet) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Packet) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Packet) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *status.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_core_factory_protos_packet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_core_factory_protos_packet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_core_factory_protos_packet_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=deadline,proto3" json:"deadline,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Hops          []*Hop                 `protobuf:"bytes,3,rep,name=hops,proto3" json:"hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_core_factory_protos_packet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_core_factory_protos_packet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_core_factory_protos_packet_proto_rawDescGZIP(), []int{2}
}

func (x *Context) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Context) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Context) GetHops() []*Hop {
	if x != nil {
		return x.Hops
	}
	return nil
}

type Hop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BinaryId      string                 `protobuf:"bytes,1,opt,name=binary_id,json=binaryId,proto3" json:"binary_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hop) Reset() {
	*x = Hop{}
	mi := &file_core_factory_protos_packet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hop) ProtoMessage() {}

func (x *Hop) ProtoReflect() protoreflect.Message {
	mi := &file_core_factory_protos_packet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hop.ProtoReflect.Descriptor instead.
func (*Hop) Descriptor() ([]byte, []int) {
	return file_core_factory_protos_packet_proto_rawDescGZIP(), []int{3}
}

func (x *Hop) GetBinaryId() string {
	if x != nil {
		return x.BinaryId
	}
	return ""
}

func (x *Hop) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_core_factory_protos_packet_proto protoreflect.FileDescriptor

const file_core_factory_protos_packet_proto_rawDesc = "" +
	"\n" +
	" core/factory/protos/packet.proto\x12\afactory\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/rpc/status.proto\"\xd3\x01\n" +
	"\x06Packet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.factory.PacketTypeR\x04type\x12$\n" +
	"\x0etarget_io_type\x18\x03 \x01(\tR\ftargetIoType\x12*\n" +
	"\acontext\x18\x04 \x01(\v2\x10.factory.ContextR\acontext\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12$\n" +
	"\x05error\x18\x06 \x01(\v2\x0e.factory.ErrorR\x05error\"3\n" +
	"\x05Error\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\"~\n" +
	"\aContext\x126\n" +
	"\bdeadline\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12 \n" +
	"\x04hops\x18\x03 \x03(\v2\f.factory.HopR\x04hops\"\\\n" +
	"\x03Hop\x12\x1b\n" +
	"\tbinary_id\x18\x01 \x01(\tR\bbinaryId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*\\\n" +
	"\n" +
	"PacketType\x12\x1b\n" +
	"\x17PACKET_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PACKET_TYPE_REQUEST\x10\x01\x12\x18\n" +
	"\x14PACKET_TYPE_RESPONSE\x10\x02B.Z,github.com/bsmider/vibe/core/factory;factoryb\x06proto3"

var (
	file_core_factory_protos_packet_proto_rawDescOnce sync.Once
	file_core_factory_protos_packet_proto_rawDescData []byte
)

func file_core_factory_protos_packet_proto_rawDescGZIP() []byte {
	file_core_factory_protos_packet_proto_rawDescOnce.Do(func() {
		file_core_factory_protos_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_factory_protos_packet_proto_rawDesc), len(file_core_factory_protos_packet_proto_rawDesc)))
	})
	return file_core_factory_protos_packet_proto_rawDescData
}

var file_core_factory_protos_packet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_factory_protos_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_core_factory_protos_packet_proto_goTypes = []any{
	(PacketType)(0),               // 0: factory.PacketType
	(*Packet)(nil),                // 1: factory.Packet
	(*Error)(nil),                 // 2: factory.Error
	(*Context)(nil),               // 3: factory.Context
	(*Hop)(nil),                   // 4: factory.Hop
	(*status.Status)(nil),         // 5: google.rpc.Status
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_core_factory_protos_packet_proto_depIdxs = []int32{
	0, // 0: factory.Packet.type:type_name -> factory.PacketType
	3, // 1: factory.Packet.context:type_name -> factory.Context
	2, // 2: factory.Packet.error:type_name -> factory.Error
	5, // 3: factory.Error.status:type_name -> google.rpc.Status
	6, // 4: factory.Context.deadline:type_name -> google.protobuf.Timestamp
	4, // 5: factory.Context.hops:type_name -> factory.Hop
	6, // 6: factory.Hop.timestamp:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_core_factory_protos_packet_proto_init() }
func file_core_factory_protos_packet_proto_init() {
	if File_core_factory_protos_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_factory_protos_packet_proto_rawDesc), len(file_core_factory_protos_packet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_factory_protos_packet_proto_goTypes,
		DependencyIndexes: file_core_factory_protos_packet_proto_depIdxs,
		EnumInfos:         file_core_factory_protos_packet_proto_enumTypes,
		MessageInfos:      file_core_factory_protos_packet_proto_msgTypes,
	}.Build()
	File_core_factory_protos_packet_proto = out.File
	file_core_factory_protos_packet_proto_goTypes = nil
	file_core_factory_protos_packet_proto_depIdxs = nil
}
